var assert = require("assert");
var progress = require("../js/progress.js");

assert.strictEqual(progress.computePercent(0, 0), null);
assert.strictEqual(progress.computePercent(100, 40), 60);
assert.strictEqual(progress.computePercent(10, 15), 0);
assert.strictEqual(progress.activeStep(null, ""), 0);
assert.strictEqual(progress.activeStep(20, ""), 1);
assert.strictEqual(progress.activeStep(70, ""), 2);
assert.strictEqual(progress.activeStep(95, ""), 3);
assert.strictEqual(progress.activeStep(10, "Starting Lua..."), 3);
assert.strictEqual(progress.isPhaseStatus("Starting Lua..."), true);
assert.strictEqual(progress.isPhaseStatus("Connecting to server"), true);
assert.strictEqual(progress.isPhaseStatus("Sending client info..."), true);
assert.strictEqual(progress.isPhaseStatus("Workshop Complete"), true);
assert.strictEqual(progress.isPhaseStatus("Mounting Addons"), true);
assert.strictEqual(progress.isPhaseStatus("Getting addon info for 123"), true);
assert.strictEqual(progress.isPhaseStatus("SEOW Content Pack"), false);
assert.strictEqual(progress.isPhaseStatus("materials/models/crate.vmt"), false);
assert.strictEqual(progress.contentLabel("Downloading 'SEOW Content Pack' via Workshop"), "SEOW Content Pack");
assert.strictEqual(progress.isFileStatus("Starting Lua..."), false);
assert.strictEqual(progress.isFileStatus("Sending client info..."), false);
assert.strictEqual(progress.isFileStatus("materials/models/crate.vmt"), true);
assert.strictEqual(progress.isFileStatus("Downloading sound/ambient/horn.wav"), true);
assert.strictEqual(progress.isFileStatus("crate.mdl"), true);
assert.strictEqual(progress.baseName("materials/models/crate.vmt"), "crate.vmt");
assert.strictEqual(progress.toSteam2("76561197960287930"), "STEAM_0:0:11101");
assert.strictEqual(progress.toSteam2("not-an-id"), "not-an-id");
assert.strictEqual(progress.parseSchemaVersion('Schema.version = "1.4.2"'), "1.4.2");
assert.strictEqual(progress.parseSchemaVersion("Schema.version = '0.9'"), "0.9");
assert.strictEqual(progress.parseSchemaVersion("Schema.name = \"SEOW\"\nSchema.version = 2"), "2");
assert.strictEqual(progress.parseSchemaVersion("Schema.name = \"SEOW\""), "");

console.log("progress tests passed");
